// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CustomCheckbox: typeof import('./src/components/CustomCheckbox.vue')['default']
    HabitDay: typeof import('./src/components/HabitDay.vue')['default']
    HabitsList: typeof import('./src/components/HabitsList.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IPhCheck: typeof import('~icons/ph/check')['default']
    IPhPlus: typeof import('~icons/ph/plus')['default']
    IPhX: typeof import('~icons/ph/x')['default']
    NewHabitForm: typeof import('./src/components/NewHabitForm.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SummaryTable: typeof import('./src/components/SummaryTable.vue')['default']
  }
}
